substitutions:
  _VERSION: 1.25.1 # default value
  _BRANCH: 1.25.1 # default value
  _CONTAINER: "cardano-node-iohk-dev"
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=chbfiv --password=$$DOCKER_API_KEY']
    secretEnv: ['DOCKER_API_KEY']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--build-arg', '_BRANCH=$_BRANCH',
           '--cache-from', 'floydcraft/$_CONTAINER:$_VERSION',
           '-t', 'floydcraft/$_CONTAINER:$COMMIT_SHA',
           '-t', 'floydcraft/$_CONTAINER:$_BRANCH',
           '-t', 'floydcraft/$_CONTAINER:$_VERSION',
           'dev']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['image', 'push', 'floydcraft/$_CONTAINER']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'alpha', 'builds', 'triggers', 'run', '--branch=$BRANCH_NAME', 'cardano-node-iohk-slim-$_VERSION' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'alpha', 'builds', 'triggers', 'run', '--branch=$BRANCH_NAME', 'cardano-py-slim' ]

timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_8'
availableSecrets:
  secretManager:
    - versionName: projects/cardano-etl/secrets/docker-chbfiv/versions/1
      env: 'DOCKER_API_KEY'